#!/usr/bin/env bash
# Publish per-image kernel/initrd to TFTP and a multi-ISO GRUB menu (NFS live trees).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TFTP_DIR="${ROOT}/data/tftp"
LIVE_ROOT="${ROOT}/data/http/live"
GRUB_DIR="${TFTP_DIR}/grub"
# shellcheck source=lib/iso-common.sh
source "${ROOT}/scripts/lib/iso-common.sh"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT}/.env"
  set +a
fi

TFTP_SERVER_IP="${TFTP_SERVER_IP:-}"
HTTP_PORT="${HTTP_PORT:-80}"
NFS_LIVE_ROOT="${NFS_LIVE_ROOT:-/var/www/html/live}"

if [[ -z "${TFTP_SERVER_IP}" ]]; then
  TFTP_SERVER_IP="192.168.1.50"
  echo "WARNING: TFTP_SERVER_IP unset; embedding ${TFTP_SERVER_IP} as GRUB fallback (set in .env)" >&2
fi

if [[ ! -f "${TFTP_DIR}/grubx64.efi" ]]; then
  echo "grubx64.efi missing; building via publish-tftp-boot.sh..."
  "${ROOT}/scripts/publish-tftp-boot.sh"
fi

shopt -s nullglob
live_dirs=()
for d in "${LIVE_ROOT}"/*/; do
  [[ -f "${d}casper/vmlinuz" ]] || continue
  live_dirs+=("${d%/}")
done

# Migrate legacy flat layout (phase 6) into a stem dir if needed
if [[ ${#live_dirs[@]} -eq 0 ]] && [[ -f "${LIVE_ROOT}/casper/vmlinuz" ]]; then
  stem="ubuntu-legacy-live"
  if [[ -f "${LIVE_ROOT}/.disk/info" ]]; then
    if grep -qi 'Server' "${LIVE_ROOT}/.disk/info"; then
      stem="ubuntu-26.04.1-live-server-amd64"
    elif grep -qi 'Desktop' "${LIVE_ROOT}/.disk/info"; then
      stem="ubuntu-26.04.1-desktop-amd64"
    fi
  fi
  echo "Migrating flat live tree → data/http/live/${stem}/"
  mkdir -p "${LIVE_ROOT}/${stem}"
  for name in casper .disk pool dists; do
    if [[ -e "${LIVE_ROOT}/${name}" ]] && [[ ! -e "${LIVE_ROOT}/${stem}/${name}" ]]; then
      mv "${LIVE_ROOT}/${name}" "${LIVE_ROOT}/${stem}/${name}"
    fi
  done
  live_dirs=("${LIVE_ROOT}/${stem}")
fi

if [[ ${#live_dirs[@]} -eq 0 ]]; then
  echo "ERROR: no extracted live trees under ${LIVE_ROOT} — run ./scripts/sync-images.sh" >&2
  exit 1
fi

# Prefer live-server as GRUB default when present (menu entry index, not image index)
prefer_stem=""
for d in "${live_dirs[@]}"; do
  stem="$(basename "${d}")"
  if [[ "${stem}" == *live-server* ]]; then
    prefer_stem="${stem}"
    break
  fi
done

mkdir -p "${GRUB_DIR}"
cfg="${GRUB_DIR}/grub.cfg.tmp"
final_cfg="${GRUB_DIR}/grub.cfg"
: >"${cfg}"

menu_count=0
default_idx=0

for live in "${live_dirs[@]}"; do
  stem="$(basename "${live}")"
  casper="${live}/casper"
  profile="$(detect_casper_profile "${casper}")" || {
    echo "WARNING: skip ${stem} (no squashfs profile)" >&2
    continue
  }
  IFS='|' read -r kind title layerfs layerfs_alt <<<"${profile}"

  if [[ -n "${prefer_stem}" && "${stem}" == "${prefer_stem}" ]]; then
    default_idx="${menu_count}"
  fi

  tftp_img="${TFTP_DIR}/images/${stem}"
  mkdir -p "${tftp_img}"
  cp -f "${casper}/vmlinuz" "${tftp_img}/vmlinuz"
  cp -f "${casper}/initrd" "${tftp_img}/initrd"
  chmod a+r "${tftp_img}/vmlinuz" "${tftp_img}/initrd"

  nfs_path="${NFS_LIVE_ROOT}/${stem}"
  if [[ "${HTTP_PORT}" == "80" ]]; then
    iso_url_line="http://\${boot_host}/iso/${stem}.iso"
  else
    iso_url_line="http://\${boot_host}:${HTTP_PORT}/iso/${stem}.iso"
  fi

  {
    echo "menuentry \"${title} (NFS)\" {"
    echo "  echo \"Loading ${stem} kernel...\""
    echo "  linux /images/${stem}/vmlinuz ip=dhcp netboot=nfs nfsroot=\${boot_host}:${nfs_path} layerfs-path=${layerfs} ---"
    echo "  initrd /images/${stem}/initrd"
    echo "}"
    echo
    echo "menuentry \"${title} (NFS, safe graphics)\" {"
    echo "  linux /images/${stem}/vmlinuz nomodeset ip=dhcp netboot=nfs nfsroot=\${boot_host}:${nfs_path} layerfs-path=${layerfs} ---"
    echo "  initrd /images/${stem}/initrd"
    echo "}"
    echo
  } >>"${cfg}"
  menu_count=$((menu_count + 2))

  if [[ -n "${layerfs_alt}" ]] && [[ -f "${casper}/${layerfs_alt}" ]]; then
    {
      echo "menuentry \"${title} (NFS, alternate layer)\" {"
      echo "  linux /images/${stem}/vmlinuz ip=dhcp netboot=nfs nfsroot=\${boot_host}:${nfs_path} layerfs-path=${layerfs_alt} ---"
      echo "  initrd /images/${stem}/initrd"
      echo "}"
      echo
    } >>"${cfg}"
    menu_count=$((menu_count + 1))
  fi

  {
    echo "menuentry \"${title} via full ISO (high RAM)\" {"
    echo "  echo \"WARNING: downloads entire ISO into client RAM\""
    echo "  linux /images/${stem}/vmlinuz ip=dhcp url=${iso_url_line} layerfs-path=${layerfs} ---"
    echo "  initrd /images/${stem}/initrd"
    echo "}"
    echo
  } >>"${cfg}"
  menu_count=$((menu_count + 1))

  echo "Menu: ${title} [${kind}] stem=${stem} layerfs=${layerfs}"
done

{
  echo "# Generated by scripts/publish-boot-chain.sh — re-run ./scripts/sync-images.sh after adding ISOs."
  echo "set timeout=20"
  echo "set default=${default_idx}"
  echo
  echo 'if [ -n "$net_default_server" ]; then'
  echo '  set boot_host=$net_default_server'
  echo 'else'
  echo "  set boot_host=\"${TFTP_SERVER_IP}\""
  echo 'fi'
  echo
  cat "${cfg}"
} >"${final_cfg}"
rm -f "${cfg}"

# Keep legacy /casper paths pointing at preferred (or first) image
def_stem="${prefer_stem:-$(basename "${live_dirs[0]}")}"
mkdir -p "${TFTP_DIR}/casper"
cp -f "${TFTP_DIR}/images/${def_stem}/vmlinuz" "${TFTP_DIR}/casper/vmlinuz"
cp -f "${TFTP_DIR}/images/${def_stem}/initrd" "${TFTP_DIR}/casper/initrd"

echo "Published GRUB → ${final_cfg} (default index ${default_idx} = ${def_stem})"
echo "Add ISOs under data/iso/ then: ./scripts/sync-images.sh"
