#!/usr/bin/env bash
# Publish kernel/initrd to TFTP and write GRUB menu for HTTP live Desktop boot.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TFTP_DIR="${ROOT}/data/tftp"
CASPER_SRC="${ROOT}/data/http/live/casper"
CASPER_TFTP="${TFTP_DIR}/casper"
GRUB_DIR="${TFTP_DIR}/grub"

# Load .env if present (do not override already-exported vars)
if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT}/.env"
  set +a
fi

UBUNTU_DESKTOP_VERSION="${UBUNTU_DESKTOP_VERSION:-26.04.1}"
ISO_NAME="ubuntu-${UBUNTU_DESKTOP_VERSION}-desktop-amd64.iso"
TFTP_SERVER_IP="${TFTP_SERVER_IP:-}"
HTTP_PORT="${HTTP_PORT:-80}"

if [[ ! -f "${CASPER_SRC}/vmlinuz" ]] || [[ ! -f "${CASPER_SRC}/initrd" ]]; then
  echo "ERROR: missing ${CASPER_SRC}/vmlinuz or initrd — run ./scripts/fetch-iso.sh first" >&2
  exit 1
fi

if [[ ! -f "${TFTP_DIR}/grubx64.efi" ]]; then
  echo "grubx64.efi missing; building via publish-tftp-boot.sh..."
  "${ROOT}/scripts/publish-tftp-boot.sh"
fi

if [[ -z "${TFTP_SERVER_IP}" ]]; then
  # Best-effort default for lab docs; GRUB also uses \$net_default_server at boot
  TFTP_SERVER_IP="192.168.1.50"
  echo "WARNING: TFTP_SERVER_IP unset; embedding ${TFTP_SERVER_IP} as GRUB fallback (set in .env)" >&2
fi

if [[ "${HTTP_PORT}" == "80" ]]; then
  HTTP_AUTHORITY="${TFTP_SERVER_IP}"
else
  HTTP_AUTHORITY="${TFTP_SERVER_IP}:${HTTP_PORT}"
fi

ISO_URL="http://${HTTP_AUTHORITY}/iso/${ISO_NAME}"
# "Try Ubuntu" live session layer (present on Desktop ISO casper/)
LAYERFS_LIVE="minimal.standard.live.squashfs"
# Full install-oriented Desktop layer (install-sources.yaml)
LAYERFS_FULL="minimal.standard.squashfs"
# Minimized Desktop
LAYERFS_MIN="minimal.squashfs"

mkdir -p "${CASPER_TFTP}" "${GRUB_DIR}"
cp -f "${CASPER_SRC}/vmlinuz" "${CASPER_TFTP}/vmlinuz"
cp -f "${CASPER_SRC}/initrd" "${CASPER_TFTP}/initrd"
chmod a+r "${CASPER_TFTP}/vmlinuz" "${CASPER_TFTP}/initrd"

cat > "${GRUB_DIR}/grub.cfg" <<EOF
# Generated by scripts/publish-boot-chain.sh — do not edit by hand; re-run the script.
# NBP: grubx64.efi  |  kernel/initrd via TFTP  |  live root via HTTP ISO URL
set timeout=15
set default=0

if [ -n "\$net_default_server" ]; then
  set http_host=\$net_default_server
else
  set http_host="${TFTP_SERVER_IP}"
fi

# Rebuild authority if DHCP next-server differs from embedded IP (port from generate time)
if [ "${HTTP_PORT}" = "80" ]; then
  set iso_url="http://\${http_host}/iso/${ISO_NAME}"
else
  set iso_url="http://\${http_host}:${HTTP_PORT}/iso/${ISO_NAME}"
fi

menuentry "Ubuntu Desktop ${UBUNTU_DESKTOP_VERSION} Live" {
  echo "Loading kernel (TFTP)..."
  linux /casper/vmlinuz ip=dhcp url=\${iso_url} layerfs-path=${LAYERFS_LIVE} ---
  echo "Loading initrd (TFTP)..."
  initrd /casper/initrd
}

menuentry "Ubuntu Desktop ${UBUNTU_DESKTOP_VERSION} Live (minimized)" {
  linux /casper/vmlinuz ip=dhcp url=\${iso_url} layerfs-path=${LAYERFS_MIN} ---
  initrd /casper/initrd
}

menuentry "Ubuntu Desktop ${UBUNTU_DESKTOP_VERSION} Live (safe graphics)" {
  linux /casper/vmlinuz nomodeset ip=dhcp url=\${iso_url} layerfs-path=${LAYERFS_LIVE} ---
  initrd /casper/initrd
}
EOF

echo "Published boot chain:"
ls -lh "${TFTP_DIR}/grubx64.efi" "${CASPER_TFTP}/vmlinuz" "${CASPER_TFTP}/initrd" "${GRUB_DIR}/grub.cfg"
echo "ISO URL (embedded fallback): ${ISO_URL}"
echo "layerfs-path (live): ${LAYERFS_LIVE}"
echo "Set TFTP_SERVER_IP in .env to your Docker host LAN IP, then re-run this script."
